name: Auto move project cards

on:
  issues:
    types:
      - opened
  pull_request_target:
    types: 
      - opened

jobs:
  auto-move-project-cards:
    uses: CommunityRP-FiveM-Server/.github/.github/workflows/auto-move-project-board.yml@main
    secrets: inherit
