name: Formatter handle web and lua files

on:
  pull_request:
    types: [ labeled ]
  
jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          
      - name: Get changed files
        id: changed-files-lua
        uses: tj-actions/changed-files@v37
        with:
          files: |
            **/*.lua
            !**/*.yml
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files-lua.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Get changed web files
        id: changed-files-web
        uses: tj-actions/changed-files@v37
        with:
          files: |
            **/*.{js,html,css,jsx}
            !**/*.yml
            !**/*.min.js
            
      - name: List all changed web files
        run: |
          for file in ${{ steps.changed-files-web.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          
    outputs:
       all-changed-files-lua-list: ${{ steps.changed-files-lua.outputs.all_changed_files }}
       any-changed-files-lua-list: ${{ steps.changed-files-lua.outputs.any_changed }}
       all-changed-files-web-list: ${{ steps.changed-files-web.outputs.all_changed_files }}
       any-changed-files-web-list: ${{ steps.changed-files-web.outputs.any_changed }}
       
  formatter-web:
    needs: get-changed-files
    uses: CommunityRP-FiveM-Server/.github/.github/workflows/formatter-web.yml@main
    if: ${{ github.event_name == 'pull_request' && github.event.label.name == 'format' }}
    with:
      all-changed-files-list: ${{ needs.get-changed-files.outputs.all-changed-files-web-list }}
      any-changed-files-list: ${{ needs.get-changed-files.outputs.any-changed-files-web-list }}
    
  formatter-lua:
    needs: get-changed-files
    uses: CommunityRP-FiveM-Server/.github/.github/workflows/formatter-lua.yml@main
    if: ${{ github.event_name == 'pull_request' && github.event.label.name == 'format' }}
    with:
      all-changed-files-list: ${{ needs.get-changed-files.outputs.all-changed-files-lua-list }}
      any-changed-files-list: ${{ needs.get-changed-files.outputs.any-changed-files-lua-list }}
      
  commit-and-push:
    needs: [get-changed-files, formatter-lua, formatter-web]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Get changed files extensions
        if: ${{ needs.get-changed-files.outputs.any-changed-files-lua-list == 'true' || needs.get-changed-files.outputs.any-changed-files-web-list == 'true'}}
        id: getext-all
        run: |
          import os
          web_files = '${{ needs.get-changed-files.outputs.all-changed-files-web-list }}'.split()
          lua_files = '${{ needs.get-changed-files.outputs.all-changed-files-lua-list }}'.split()
          all_files = web_files + lua_files
          extensions = set('*' + os.path.splitext(file)[1] for file in all_files)
          with open(os.getenv('GITHUB_ENV'), 'a') as f:
            f.write(f"CHANGED_EXTENSIONS={' '.join(extensions)}\n")
        shell: python

      - name: Create or Update .gitignore
        run: |
          echo "node_modules/" >> .gitignore
          echo "package.json" >> .gitignore
          echo "package-lock.json" >> .gitignore        

      - name: Commit changes and push current branch
        if: ${{ needs.get-changed-files.outputs.any-changed-files-lua-list == 'true' || needs.get-changed-files.outputs.any-changed-files-web-list == 'true'}}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: ESX GITHUB ACTIONS BOT
          commit_user_email: esx-github-actions-bot@users.noreply.github.com
          commit_message: :art:Code formatted in ${{ env.CHANGED_EXTENSIONS }} files
          file_pattern: ${{ env.CHANGED_EXTENSIONS }}
          status_options: '--untracked-files=no'
    
      
