name: Formatter handle web and lua files

on:
  pull_request:
    types: [ labeled ]
  
jobs:
  formatter-web:
    uses: CommunityRP-FiveM-Server/.github/.github/workflows/formatter-web.yml@main
    if: ${{ github.event_name == 'pull_request' && github.event.label.name == 'format' }}
