name: Add bugs to bugs project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_STATE
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/CommunityRP-FiveM-Server/projects/8
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
        id: add-project
      - uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/orgs/CommunityRP-FiveM-Server/projects/8
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          item-id: ${{ steps.add-project.outputs.itemId }}
          field-keys: Date
          field-values: ${{ env.date }},
