name: Simple Release

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version Number'
        required: false
        default: ''
      zipName:
        description: 'Zip Name'
        required: true
        default: 'esx_core'
      web:
        description: 'Web'
        required: false
        default: 'false'

jobs:
  simple-create-release:
    uses: CommunityRP-FiveM-Server/.github/.github/workflows/simple-release.yml@main
    with:
      zipName: ${{ github.event.inputs.zipName }}
      web: ${{ github.event.inputs.web }}
      versionNumber: ${{ github.event.inputs.versionNumber }}

