name: Simple Release

on:
  issues:
    types:
      - opened
  
jobs:
  simple-create-release:
    uses: CommunityRP-FiveM-Server/.github/.github/workflows/simple-release.yml@main
    with:
      zipName: 'esx_core'
      web: true
